# Generated by Django 3.2.13 on 2022-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('EpsId', models.AutoField(primary_key=True, serialize=False)),
                ('EpsName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('UserDocument', models.FloatField(max_length=50)),
                ('UserPassword', models.CharField(max_length=500)),
                ('UserGenre', models.CharField(max_length=500)),
                ('UserDateOfBorn', models.CharField(max_length=500)),
                ('UserPhone', models.FloatField(max_length=50)),
                ('UserEpsId', models.CharField(max_length=500)),
                ('UserRoleId', models.CharField(max_length=500)),
                ('UserCreation', models.CharField(max_length=500)),
            ],
        ),
    ]
